services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intellishop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/intellishop
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db

volumes:
  pgdata: